"""add appealing and failed to submissionstatus enum

Revision ID: 12df1ae8a34a
Revises: a7987bb2d365
Create Date: 2025-04-01 04:43:47.564943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12df1ae8a34a'
down_revision: Union[str, None] = 'a7987bb2d365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
